services:

  db:
    image: mysql:8.4
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sp-rl
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./outros/sp-rl.sql:/docker-entrypoint-initdb.d/sp-rl.sql:ro


  php:
    build: .
    container_name: php-app
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html:cached

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
